services:
  - type: web
    name: portfolio-django
    env: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn portfolio_site.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
